#!/bin/bash
#+
# This script is intended to be invoked via QjackCtl to start up and
# shut down JACK on a system running PulseAudio. It handles the
# necessary setup to make the two work together, so PulseAudio clients
# get transparently routed through JACK while the latter is running, or
# if pulseaudio is suspend by pasuspender, do nothing
#
# Usage: in QjackCtl’s Settings window, in the “Options” tab, enter
# the command
#
# pajackconnect start &
#
# in the field labelled “Execute script after Startup”, and put
#
# pajackconnect stop &
#
# in the field labelled “Execute script on Shutdown”.
#
# pajackconnect reset &
#
# in the field labelled “Execute script after Shutdown”.
#
# for use jack without pulseaudio, add in Qjackctl setting window 
# in the serverpath field 'pasuspender -- ' before 'jackd', save settings 
# as "No Pulse" for example. Remove 'pasuspender -- ', 
# and save settings as 'Pulse'. Now you can select from the 
# Qjackctl setting window, if you would start jack with or without pulse.
#
# References:
# PulseAudio: <http://www.freedesktop.org/wiki/Software/PulseAudio/>
# JACK: <http://jackaudio.org/>
#
# Copyright 2014 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#
# added possibility to run jack without pulse by Hermann Meyer
#-


# check for given command-line option
if [ "$#" == 1 ]; then
	cmd="$1"
else
	cmd=
fi
if [ "$cmd" != "start" -a "$cmd" != "stop" -a "$cmd" != "reset" ]; then
	echo $'Usage:\n\t'"$0"$' start|stop|reset\n' 1>&2
	exit 3
fi

# variable to fetch pasuspender status 
p=`ps ax | grep pasuspender`

# if command-line option start is given
if [ "$cmd" = "start" ]; then
	# check if pasuspender waiting for jack, if so, exit here. Nothing more
	# to do.
	if [[ "$p"  =~ "jackd" ]]; then
		#echo "pasuspender is active"
		exit
	else
		# if pasuspender isn't waiting for jack, let's fetch the current
		# ports, pulseaudio use, save them to /tmp, for later use.
		#echo "pasuspender is NOT active"
		sink=`pacmd list short sinks |  sed -n "/Default sink name/p"| sed "s/Default sink name://"`
		`echo $sink >/tmp/pasinkj`
		source=`pacmd list short sinks |  sed -n "/Default source name/p"| sed "s/Default source name://"`
		`echo $source >/tmp/pasourcej`
		# load the pulseaudio jack module and set them as default ports
		pacmd load-module module-jack-sink channels=2
		pacmd load-module module-jack-source channels=2
		pacmd unload-module module-suspend-on-idle
		pacmd set-default-sink jack_out
		# move around source port, seems to make pulseaudio work with jack
		# otherwise it seems that pulseaudio is connected, but it didn't work.
		pacmd set-default-source jack_in && sleep 1
		pacmd set-default-source $source && sleep 1
		pacmd set-default-source jack_in
		#echo "pa source switched"
	fi
# if command-line option stop is given
elif [ "$cmd" = "stop" ]; then
	# again, check if pasuspender waiting for jack, if not, unload the pulse
	# jack module and reload the module-suspend-on-idle. 
	if [[ ! "$p"  =~ "jackd" ]]; then
		#echo "pasuspender is NOT active"
		pacmd unload-module module-jack-sink
		pacmd unload-module module-jack-source
		pacmd load-module module-suspend-on-idle
	else
		# if pasuspender waiting for jack, add a timeout to pasuspender
		# to allow a smooth reset action afterward. 
		#echo "pasuspender is active"
		pasuspender -- sleep 5 &
	fi
# if command-line option reset is given
elif [ "$cmd" = "reset" ]; then
	# check if we have add a timeout to pasuspender, if so, exit here.
	if [[ "$p"  =~ "sleep" ]]; then
		#echo "pasuspender is active"
		exit
	else
		# fetch the previous saved pulse audio ports and set them back 
		# as default ports for pulseaudio. Done.
		sink=`cat /tmp/pasinkj`
		source=`cat /tmp/pasourcej`
		pacmd set-default-sink $sink 
		pacmd set-default-source $source 
		#echo "pasuspender is NOT active"
	fi
fi
