#!/bin/sh
# postinst script for pajackconnect
#
# see: dh_installdeb(1)

set -e
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask resume-fix-pulseaudio.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled resume-fix-pulseaudio.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
    user="$(logname)"
    id=`id -u $(logname)`
    sed -i 's/USERNAME/'"$(logname)"'/' "/etc/systemd/system/resume-fix-pulseaudio.service"
    sed -i 's/USERID/'"$(id -u $(logname))"'/' "/etc/systemd/system/resume-fix-pulseaudio.service"
	deb-systemd-helper enable resume-fix-pulseaudio.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
    user="$(logname)"
    id=`id -u $(logname)`
    sed -i 's/USERNAME/'"$(logname)"'/' "/etc/systemd/system/resume-fix-pulseaudio.service"
    sed -i 's/USERID/'"$(id -u $(logname))"'/' "/etc/systemd/system/resume-fix-pulseaudio.service"
	deb-systemd-helper update-state resume-fix-pulseaudio.service >/dev/null || true
fi
# End automatically added section


exit 0
